### ISSUE TITLE
Investigate Test Failures Between Riak 2.1 and the .Net Client [JIRA: CLIENTS-363]

### ISSUE THREAD

**Issue by Basho-JIRA** [basho/riak-dotnet-client#271]
Currently seeing failures when running the .Net Client test suite against Riak 2.1.

Failures observed:

 1) SetUp Failure : RiakClientTests.Live.MapReduce.WhenUsingSearchAsInput
      Unable to access functioning Riak node
 at RiakClientTests.Extensions.ShouldBeTrue(Boolean value, String message) in c:\Dev\riak-dotnet-client\src\RiakClientTests\Extensions.cs:line 83
 at RiakClientTests.Live.MapReduce.WhenUsingSearchAsInput.LoadDataIntoRiak() in c:\Dev\riak-dotnet-client\src\RiakClientTests.Live\MapReduce\WhenUsingSearchAsInput.cs:line 116
 at RiakClientTests.Live.MapReduce.WhenUsingSearchAsInput.SetUp() in c:\Dev\riak-dotnet-client\src\RiakClientTests.Live\MapReduce\WhenUsingSearchAsInput.cs:line 61

(And dependent tests in that file)

Also all tests in RiakClientTests.Live.Search.TestSearchAdminOperations are giving faulures.

**[Created in JIRA by Alexander Moore]**

**Comment by Basho-JIRA** [comment]
Duplicated by CLIENTS-407 

***[posted via JIRA by Luke Bakken]***
